const marvelCharacters = [
    "Spider-Man",
    "Iron Man",
    "Captain America",
    "Thor",
    "Hulk",
    "Black Widow",
    "Hawkeye",
    "Doctor Strange",
    "Black Panther",
    "Scarlet Witch",
    "Vision",
    "Ant-Man",
    "Wasp",
    "Captain Marvel",
    "Falcon",
    "Winter Soldier",
    "War Machine",
    "Star-Lord",
    "Gamora",
    "Drax",
    "Rocket Raccoon",
    "Groot",
    "Mantis",
    "Nebula",
    "Yondu",
    "Nick Fury",
    "Maria Hill",
    "Phil Coulson",
    "Loki",
    "Thanos",
    "Ultron",
    "Red Skull",
    "Green Goblin",
    "Doctor Octopus",
    "Sandman",
    "Venom",
    "Carnage",
    "Rhino",
    "Mysterio",
    "Electro",
    "Lizard",
    "Kingpin",
    "Bullseye",
    "Mystique",
    "Magneto",
    "Sabretooth",
    "Juggernaut",
    "Deadpool",
    "Cable",
    "Domino",
];

const dragonBallCharacters = [
    "Goku",
    "Vegeta",
    "Gohan",
    "Piccolo",
    "Krillin",
    "Bulma",
    "Master Roshi",
    "Tien Shinhan",
    "Yamcha",
    "Chiaotzu",
    "Android 18",
    "Android 17",
    "Frieza",
    "Cell",
    "Majin Buu",
    "Trunks",
    "Future Trunks",
    "Goten",
    "Pan",
    "Videl",
    "Chi-Chi",
    "Beerus",
    "Whis",
    "Jiren",
    "Broly",
    "Bardock",
    "Raditz",
    "Nappa",
    "King Kai",
    "Supreme Kai",
    "Dende",
    "Kami",
    "Mr. Popo",
    "Hercule (Mr. Satan)",
    "Shenron",
    "Porunga",
    "King Yemma",
    "Korun",
    "Yajirobe",
    "Launch",
    "Fortuneteller Baba",
    "Ginyu",
    "Recoome",
    "Burter",
    "Jeice",
    "Guldo",
    "Zarbon",
    "Dodoria",
    "Pui Pui",
    "Supreme Kai of Time",
];

const pokemonCharacters = [
    "Bulbasaur",
];

// const pokemonCharacters = [
//     "Bulbasaur",
//     "Charmander",
//     "Squirtle",
//     "Caterpie",
//     "Weedle",
//     "Pidgey",
//     "Rattata",
//     "Spearow",
//     "Ekans",
//     "Pikachu",
//     "Sandshrew",
//     "Nidoran♀",
//     "Nidoran♂",
//     "Clefairy",
//     "Vulpix",
//     "Jigglypuff",
//     "Zubat",
//     "Oddish",
//     "Paras",
//     "Venonat",
//     "Diglett",
//     "Meowth",
//     "Psyduck",
//     "Mankey",
//     "Growlithe",
//     "Poliwag",
//     "Abra",
//     "Machop",
//     "Bellsprout",
//     "Tentacool",
//     "Geodude",
//     "Ponyta",
//     "Slowpoke",
//     "Magnemite",
//     "Farfetch'd",
//     "Doduo",
//     "Seel",
//     "Grimer",
//     "Shellder",
//     "Gastly",
//     "Onix",
//     "Drowzee",
//     "Krabby",
//     "Voltorb",
//     "Exeggcute",
//     "Cubone",
//     "Hitmonlee",
//     "Hitmonchan",
//     "Lickitung",
//     "Koffing",
// ];

const narutoCharacters = [
    "Naruto Uzumaki",
    "Sasuke Uchiha",
    "Sakura Haruno",
    "Kakashi Hatake",
    "Hinata Hyuga",
    "Shikamaru Nara",
    "Ino Yamanaka",
    "Choji Akimichi",
    "Kiba Inuzuka",
    "Shino Aburame",
    "Rock Lee",
    "Tenten",
    "Neji Hyuga",
    "Gaara",
    "Temari",
    "Kankuro",
    "Jiraiya",
    "Tsunade",
    "Orochimaru",
    "Itachi Uchiha",
    "Kisame Hoshigaki",
    "Deidara",
    "Sasori",
    "Hidan",
    "Kakuzu",
    "Konan",
    "Pain",
    "Zetsu",
    "Madara Uchiha",
    "Obito Uchiha",
    "Minato Namikaze",
    "Kushina Uzumaki",
    "Hiruzen Sarutobi",
    "Asuma Sarutobi",
    "Kurenai Yuhi",
    "Iruka Umino",
    "Konohamaru Sarutobi",
    "Might Guy",
    "Yamato",
    "Sai",
    "Danzo Shimura",
    "Kabuto Yakushi",
    "Haku",
    "Zabuza Momochi",
    "Mei Terumi",
    "A (Fourth Raikage)",
    "Killer Bee",
    "Onoki",
    "Akatsuchi",
    "Kurotsuchi",
];

const digimonCharacters = [
    "Agumon",
    "Gabumon",
    "Biyomon",
    "Tentomon",
    "Palmon",
    "Gomamon",
    "Patamon",
    "Gatomon",
    "Veemon",
    "Hawkmon",
    "Armadillomon",
    "Wormmon",
    "Guilmon",
    "Terriermon",
    "Renamon",
    "Impmon",
    "Lopmon",
    "Monodramon",
    "Agunimon",
    "Lobomon",
    "Kazemon",
    "Beetlemon",
    "Kumamon",
    "Flamon",
    "Strabimon",
    "Takuya Kanbara",
    "Koji Minamoto",
    "Zoe Orimoto",
    "J.P. Shibayama",
    "Tommy Himi",
    "Marcus Damon",
    "Thomas H. Norstein",
    "Yoshino Fujieda",
    "Keenan Crier",
    "Shoutmon",
    "Ballistamon",
    "Dorulumon",
    "Cutemon",
    "Mikey Kudo",
    "Angie Hinomoto",
    "Jeremy Tsurgi",
    "Tagiru Akashi",
    "Gumdramon",
    "Ren Tobari",
    "Airu Suzaki",
    "Mimi Tachikawa",
    "Joe Kido",
    "Matt Ishida",
    "Sora Takenouchi",
    "Izzy Izumi",
];

const caballerosDelZodiacoCharacters = [
    "Seiya de Pegaso",
    "Shiryu de Dragón",
    "Hyoga de Cisne",
    "Shun de Andrómeda",
    "Ikki de Fénix",
    "Saori Kido / Atenea",
    "Aioria de Leo",
    "Milo de Escorpio",
    "Aioros de Sagitario",
    "Shaka de Virgo",
    "Camus de Acuario",
    "Shura de Capricornio",
    "Saga de Géminis",
    "Mu de Aries",
    "Aldebarán de Tauro",
    "Deathmask de Cáncer",
    "Dohko de Libra",
    "Máscara de Muerte de Cáncer",
    "Afrodita de Piscis",
    "Athena / Saori Kido",
    "Hilda de Polaris",
    "Frey de Surt",
    "Fenrir de Alioth",
    "Hagen de Merak",
    "Mime de Benetnasch",
    "Alberich de Megrez",
    "Siegfried de Dubhe",
    "Pandora",
    "Shion de Aries",
    "Kiki",
    "Hyoga del Cisne",
    "Mu de Aries",
    "Shiryu del Dragón",
    "Ikki del Fénix",
    "Shun de Andrómeda",
    "Sorento de Sirena",
    "Radamanthys de Wyvern",
    "Minos de Grifo",
    "Aiacos de Garuda",
    "Hades",
    "Thanatos",
    "Hypnos",
    "Sisifo de Sagitario",
    "Aspros de Géminis",
    "Deuteros de Géminis",
    "Manigoldo de Cáncer",
    "Regulus de Leo",
    "Asmita de Virgo",
    "Dohko de Libra",
    "Shion de Aries",
    "Tenma de Pegaso",
    "Alone",
    "Yuzuriha de Grulla",
    "Hakurei de Altar",
    "Aiacos de Garuda",
    "Valentine de Arpía",
    "Tetis de Sirena",
    "Unity de Dragón",
    "Lune de Balrog",
    "Niobe de Deep",
    "Docrates de Cisne",
    "Vermeer de Grifo",
    "Christ de Crisaor",
    "Caronte de Aqueronte",
    "Cheshire de Cait Sith",
    "Krisna de Crisaor",
    "Lima de Cefeo",
    "Agora de Loto",
    "David de Auriga",
    "Albafica de Piscis",
    "Kardia de Escorpio",
    "El Cid de Capricornio",
    "Shiryu del Dragón",
    "Hyoga del Cisne",
    "Shun de Andrómeda",
    "Ikki del Fénix",
    "Saori Kido",
    "Aioria de Leo",
    "Milo de Escorpio",
    "Aioros de Sagitario",
    "Shaka de Virgo",
    "Camus de Acuario",
    "Shura de Capricornio",
    "Saga de Géminis",
    "Mu de Aries",
    "Aldebarán de Tauro",
    "Máscara de Muerte de Cáncer",
    "Afrodita de Piscis",
];

const rickAndMortyCharacters = [
    "Rick Sanchez",
    "Morty Smith",
    "Summer Smith",
    "Jerry Smith",
    "Beth Smith",
    "Birdperson",
    "Squanchy",
    "Mr. Meeseeks",
    "Mr. Poopybutthole",
    "Unity",
    "Tammy Gueterman",
    "Phoenixperson",
    "Evil Morty",
    "Doofus Rick",
    "Abradolf Lincler",
    "Gearhead",
    "Noob-Noob",
    "Scary Terry",
    "Krombopulos Michael",
    "Snowball",
    "Abradolf Lincler",
    "Ants in My Eyes Johnson",
    "Cromulon",
    "Gazorpazorpfield",
    "Jerryboree Receptionist",
    "Jessica",
    "Principal Vagina",
    "Beth's Mytholog",
    "Blamphs",
    "Brad Anderson",
    "Chewbacca",
    "Coach Feratu",
    "Crocubot",
    "Dr. Glip-Glop",
    "Ethan",
    "Fart",
    "Frankenstein's Monster",
    "Gar Gloonch",
    "Giant Telepathic Spiders",
    "Ghost in a Jar",
    "Giant Head",
    "Giant Testicle Monster",
    "Hammerhead Morty",
    "Hemorrhage",
    "Hunter",
    "Jaguar",
    "King Jellybean",
    "Korblock",
    "Krombopulos Michael",
    "Lucius Needful",
];

const demonSlayerCharacters = [
    "Tanjiro Kamado",
    "Nezuko Kamado",
    "Zenitsu Agatsuma",
    "Inosuke Hashibira",
    "Giyu Tomioka",
    "Kanao Tsuyuri",
    "Shinobu Kocho",
    "Kyojuro Rengoku",
    "Tengen Uzui",
    "Muichiro Tokito",
    "Genya Shinazugawa",
    "Sanemi Shinazugawa",
    "Mitsuri Kanroji",
    "Obanai Iguro",
    "Gyomei Himejima",
    "Sakonji Urokodaki",
    "Sabito",
    "Makomo",
    "Hanako Kamado",
    "Kie Kamado",
    "Jigoro Kuwajima",
    "Hotaru Haganezuka",
    "Kozo Kanamori",
    "Tokie Kamado",
    "Sumiyoshi",
    "Yushiro",
    "Tamayo",
    "Yushiro",
    "Muzan Kibutsuji",
    "Upper Moon One - Kokushibo",
    "Upper Moon Two - Doma",
    "Upper Moon Three - Akaza",
    "Upper Moon Four - Hantengu",
    "Upper Moon Five - Gyokko",
    "Upper Moon Six - Daki",
    "Upper Moon Seven - Enmu",
    "Upper Moon Eight - Rokuro",
    "Upper Moon Nine - Kaigaku",
    "Lower One - Kyogai",
    "Lower Two - Mukago",
    "Lower Three - Rui",
    "Lower Five - Gluttony",
    "Lower Six - Swamp Demon",
    "Lower Twelve - Temari Demon",
    "Hand Demon",
    "Father Spider Demon",
    "Mother Spider Demon",
    "Daughter Spider Demon",
    "Son Spider Demon",
    "Elder Brother Spider Demon",


];

const barbieCharacters = [
    "Barbie",
    "Ken",
    "Skipper",
    "Stacie",
    "Chelsea",
    "Teresa",
    "Christie",
    "Midge",
    "Raquelle",
    "Ryan",
    "Nikki",
    "Tiffany",
    "Grace",
    "Summer",
    "Blaine",
    "Steven",
    "Kelly",
    "Tommy",
    "Todd",
    "Shelly",
    "George Roberts",
    "Margaret Roberts",
    "Skipper Roberts",
    "Stacie Roberts",
    "Chelsea Roberts",
    "Tutti",
    "Francie",
    "PJ",
    "Alan",
    "Miko",
    "Becky",
    "Courtney",
    "Cassandra",
    "Drew",
    "Janet",
    "Teresa Rivera",
    "Nia",
    "Daisy",
    "Renee",
    "Kayla",
    "Nikki O'Neill",
    "Giselle",
    "Lara",
    "Bella",
    "Kira",
    "Tia",
    "Lacey",
    "Lara",
    "Dee Dee",
    "Marissa",

 
];

const mixedCharacters = [
    // Marvel
    "Iron Man",
    "Captain America",
    "Thor",
    "Hulk",
    "Black Widow",
    "Hawkeye",
    "Spider-Man",
    "Black Panther",
    "Doctor Strange",
    "Captain Marvel",
    "Scarlet Witch",
    "Vision",
    "Wolverine",
    "Deadpool",
    "Thanos",
    "Loki",
    "Magneto",
    "Professor X",
    "Groot",
    "Rocket Raccoon",
    "Gamora",
    "Star-Lord",
    "Drax",
    "Nick Fury",
    "Ant-Man",
    "Wasp",
    "Falcon",
    "Winter Soldier",
    "Doctor Doom",
    "Daredevil",
    "Luke Cage",
    "Jessica Jones",
    "Iron Fist",
    "Punisher",
    "Ghost Rider",
    "Blade",
    "Cyclops",
    "Jean Grey",
    "Storm",
    "Rogue",
    "Gambit",
    "Nightcrawler",
    "Beast",
    "Iceman",
    "Colossus",

    // Dragon Ball
    "Goku",
    "Vegeta",
    "Piccolo",
    "Gohan",
    "Trunks",
    "Goten",
    "Krillin",
    "Tien",
    "Yamcha",
    "Chiaotzu",
    "Bulma",
    "Chi-Chi",
    "Android 18",
    "Majin Buu",
    "Frieza",
    "Cell",
    "Beerus",
    "Whis",
    "Master Roshi",
    "Oolong",
    "Puar",
    "Raditz",
    "Nappa",
    "King Kai",
    "Bardock",
    "Broly",
    "Pan",
    "Videl",
    "Mr. Satan",
    "Uub",
    "Dende",
    "Shenron",
    "Zeno",

    // Pokémon
    "Pikachu",
    "Charizard",
    "Bulbasaur",
    "Squirtle",
    "Jigglypuff",
    "Meowth",
    "Mewtwo",
    "Eevee",
    "Snorlax",
    "Gyarados",
    "Mew",
    "Lugia",
    "Ho-Oh",
    "Rayquaza",
    "Groudon",
    "Kyogre",
    "Lucario",
    "Garchomp",
    "Greninja",
    "Charmander",
    "Sylveon",
    "Gardevior",
    "Alakazam",
    "Gengar",
    "Magikarp",
    "Dragonite",
    "Metagross",
    "Tyranitar",
    "Arcanine",
    "Psyduck",
    "Mudkip",
    "Rowlet",
    "Infernape",
    "Decidueye",
    "Gardevoir",

    // Naruto
    "Naruto Uzumaki",
    "Sasuke Uchiha",
    "Sakura Haruno",
    "Kakashi Hatake",
    "Hinata Hyuga",
    "Shikamaru Nara",
    "Ino Yamanaka",
    "Choji Akimichi",
    "Kiba Inuzuka",
    "Shino Aburame",
    "Rock Lee",
    "Neji Hyuga",
    "Gaara",
    "Tenten",
    "Jiraiya",
    "Tsunade",
    "Orochimaru",
    "Itachi Uchiha",
    "Deidara",
    "Sasori",
    "Hidan",
    "Kakuzu",
    "Konan",
    "Pain",
    "Madara Uchiha",
    "Minato Namikaze",
    "Kushina Uzumaki",
    "Asuma Sarutobi",
    "Kurenai Yuhi",
    "Iruka Umino",
    "Konohamaru Sarutobi",
    "Might Guy",
    "Yamato",
    "Sai",
    "Danzo Shimura",
    "Kabuto Yakushi",
    "Haku",
    "Zabuza Momochi",
    "Mei Terumi",
    "Killer Bee",
    "Onoki",

    // Digimon
    "Agumon",
    "Gabumon",
    "Biyomon",
    "Tentomon",
    "Palmon",
    "Gomamon",
    "Patamon",
    "Gatomon",
    "Veemon",
    "Hawkmon",
    "Armadillomon",
    "Wormmon",
    "Guilmon",
    "Terriermon",
    "Renamon",
    "Impmon",
    "Lopmon",
    "Monodramon",
    "Agunimon",
    "Lobomon",
    "Kazemon",
    "Beetlemon",
    "Kumamon",
    "Flamon",
    "Strabimon",
    "Shoutmon",
    "Ballistamon",
    "Dorulumon",
    "Cutemon",

    // Naruto
    "Tanjiro Kamado",
    "Nezuko Kamado",
    "Zenitsu Agatsuma",
    "Inosuke Hashibira",
    "Giyu Tomioka",
    "Kanao Tsuyuri",
    "Shinobu Kocho",
    "Kyojuro Rengoku",
    "Tengen Uzui",
    "Muichiro Tokito",
    "Genya Shinazugawa",
    "Sanemi Shinazugawa",
    "Mitsuri Kanroji",
    "Obanai Iguro",
    "Gyomei Himejima",

    // Barbie
    "Barbie",
    "Ken",
    "Skipper",
    "Stacie",
    "Chelsea",
    "Teresa",
    "Christie",
    "Midge",
    "Raquelle",
    "Ryan",

    // Peppa Pig
    "Peppa Pig",
    "George Pig",
    "Mummy Pig",
    "Daddy Pig",
    "Suzy Sheep",
    "Rebecca Rabbit",
    "Danny Dog",
    "Pedro Pony",
    "Emily Elephant",
    "Candy Cat",

    // InuYasha
    "InuYasha",
    "Kagome Higurashi",
    "Miroku",
    "Sango",
    "Shippo",
    "Sesshomaru",
    "Kikyo",
    "Naraku",
    "Koga",
    "Kirara",

    // Yu-Gi-Oh!
    "Yugi Muto",
    "Yami Yugi (Pharaoh Atem)",
    "Seto Kaiba",
    "Joey Wheeler (Katsuya Jonouchi)",
    "Tea Gardner (Anzu Mazaki)",
    "Tristan Taylor (Hiroto Honda)",
    "Bakura Ryou",
    "Marik Ishtar",
    "Mai Valentine (Mai Kujaku)",
    "Yami Bakura",
    "Maximillion Pegasus",
    "Serenity Wheeler (Shizuka Kawai)",
    "Duke Devlin (Ryuji Otogi)",
    "Mokuba Kaiba",
    "Grandpa (Solomon Muto)",
    "Rex Raptor (Dinosaur Ryuzaki)",
    "Weevil Underwood (Insector Haga)",
    "Espa Roba",
    "Bandit Keith (Keith Howard)",

    // Rick and Morty
    "Rick Sanchez",
    "Morty Smith",
    "Summer Smith",
    "Jerry Smith",
    "Beth Smith",
    "Birdperson",
    "Squanchy",
    "Mr. Meeseeks",
    "Mr. Poopybutthole",
    "Unity",
    "Tammy Gueterman",
    "Phoenixperson",
    "Evil Morty",
    "Doofus Rick",
    "Abradolf Lincler",
    "Gearhead",
    "Noob-Noob",
    "Scary Terry",
    "Krombopulos Michael",
    "Snowball",
    "Ants in My Eyes Johnson",

    // Demon Slayer
    "Tanjiro Kamado",
    "Nezuko Kamado",
    "Zenitsu Agatsuma",
    "Inosuke Hashibira",
    "Giyu Tomioka",
    "Kanao Tsuyuri",
    "Shinobu Kocho",
    "Kyojuro Rengoku",
    "Tengen Uzui",
    "Muichiro Tokito",
    "Genya Shinazugawa",
    "Sanemi Shinazugawa",

    // Peppa Pig (Repetidos para llegar a 100)
    "Suzy Sheep",
    "Rebecca Rabbit",
    "Danny Dog",
    "Pedro Pony",
    "Emily Elephant",
    "Candy Cat",
    "Zoe Zebra",
    "Richard Rabbit",
    "Freddie Fox",
    "Wendy Wolf"
];
